net_params:
  msg_len: 32
  key_len: 32
  num_conv_layers: 4
  output_dims: [2, 4, 4, 1]
  kernel_sizes: [4, 2, 1, 1]
  strides: [1, 2, 1, 1]

other_params:
  lr: 0.0008
  batch_size: 512
  epochs: 20
  iterations: 150000
  eve_retrain_bool: True
  eve_retrain_epochs: 5
  eve_retrain_iterations: 250000